### ISSUE TITLE
chickpeamine is outside the circle of legume friends?

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-chickpeamine#2]
for example, everyone else is very cordial to this peanut gene:
https://mines.legumeinfo.org/peanutmine/portal.do?class=Gene&externalids=Aradu.68YSI
and it looks like there are chickpea genes who want to be friends:
https://legumeinfo.org/chado_phylotree/phytozome_10_2.59211447?hilite_node=aradu.Aradu.68YSI.1

someone is making the effort (if you're patient enough):
https://mines.legumeinfo.org/chickpeamine/portal.do?class=Gene&externalids=Ca_24703_gene

the two things that seem significant as to underlying cause:
no chickpea gene homologues appear in the peanut (or bean and probably others) gene page:
https://mines.legumeinfo.org/peanutmine/portal.do?externalids=Aradu.68YSI&class=Gene&origin=ChickpeaMine
(while the chickpea gene page does have the homologues listed to the other species)

chickpeamine does not even appear in the list of Links to other Mines in the peanut gene page.

it's as if they are allergic to falafel?! that's pretty rich, esp. coming from a species like peanut.

**Comment by sammyjava** [comment]
Those are ancient mines. We're testing mines on chama, not production, pay no attention to behavior of production mines. Those homologies will appear when those mines are rebuilt with the new set of organisms.

**Comment by adf-ncgr** [comment]
there's nothing worse than moldy falafel
