### ISSUE TITLE
expression not expressing on gene pages

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-chickpeamine#3]
https://chama:8443/chickpeamine/portal.do?class=Gene&externalids=ICC4958.Ca_09064
no expression display in evidence; this is a desi gene, so I'd expect to see something; for a kabuli gene there is an error message instead, which presumably is because we don't have kabuli expression data
https://chama:8443/chickpeamine/portal.do?class=Gene&externalids=CDCFrontier.Ca_07836

I can live without for purposes of my epic, given that Sudhansu's updates to the gene pages in legumeinfo are performing the needed function; just thought I should point it out

**Comment by sammyjava** [comment]
Yup, on my list. And I want to make the kabuli displayer fail silently.

**Comment by sammyjava** [comment]
Oh, I fixed this by switching to GeneBarchartDisplayer. May have closed another issue thinking it was this one!
