### ISSUE TITLE
gene renaming (minor)

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-chickpeamine#4]
Glad to see you dealt with the chickpea naming and thought to adjust the linkout
calls until the naming in LIS catches up (which might be easy, unless there are files needing updated in the datastore
to match, but I suspect whatever we have there is already inconsistent with the chado, so not a big concern); it does however
mean I need to fix the linkout mechanism to go from other parts of LIS to chickpeamine, though (which is also easy);
and you need to change the example searches on the front page of chickpeamine which I think need CDCFrontier. prepended:
Examples: Ca_00369, Ca_00369_gene

not sure if there may be other minor places to address, but these were the first I thought of

**Comment by sammyjava** [comment]
I think this issue was auto-deprecated by the adoption of chado.feature.name=secondaryIdentifier and whatever munging on chado.feature.uniquename -> primaryIdentifier. In any case, that's the standard now.
