### ISSUE TITLE
GWAS data set

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-chickpeamine#5]
per our recent discussion, the recent publication on which Eric vW was one of the authors is: https://www.nature.com/articles/s41588-019-0401-3

I don't have access to it at the moment but my recollection is that there was a fairly typical GWAS result for a set of traits in some tabular form amenable to Manhattanization.

your mission, which you already chose to accept on behalf of the Data Store. thanks!

**Comment by sammyjava** [comment]
This publication appears on the latest ChickpeaMine so I presume that I grabbed this GWAS. :)
